FROM golang:1.8-alpine

RUN apk add --no-cache git && go get github.com/Masterminds/glide
WORKDIR /go/src/github.com/ory-am/hydra

ADD . .
RUN ls
RUN go install .

ENTRYPOINT /go/bin/hydra host --dangerous-auto-logon --dangerous-force-http

EXPOSE 4444
